### PR TITLE
Fix access validation

### PR DESCRIPTION
**Pull request by mootrichard**
Fix access to validation_results being available outside of package, since you need accessors for retrieving data mapped there.

### CODE REVIEW

**Comment by donbeave** [comment]
@sbeidas @assislucas any chance this PR will be merged?

**Comment by assislucas** [comment]
@donbeave Sorry for the delay moving this PR forward. Since it now became old, before we can evaluate it to be merged, it needs to be updated with current master and we need to check the unit test results.

**Comment by donbeave** [comment]
@assislucas do you need help with this? I hope I can help you guys, don't want to wait one more year for such small fixes.

Here is also some problems, like using `Object` type instead of `String` type: 
https://github.com/goshippo/shippo-java-client/blob/master/src/main/java/com/shippo/model/Address.java#L23

And this PR is only adding some getters and setters to some private fields, otherwise, there is no normal way to get status from address validation response, because field `is_valid` is private.

**Comment by muzuro** [comment]
Hi! Any updates?

**Comment by assislucas** [comment]
@muzuro We are planning to update this PR and get it merged soon.

**Pull request closed without merging**
